name: Java Hello World CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t hello-java-app .

      - name: Run Docker Compose
        run: docker compose up --build -d
